### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by preethi-shekar** [salesforce/refocus#1118]
After setting up the refocus locally : https://opensource.salesforce.com/refocus/docs/04-quickstartlocal.html

Postgres and Redis are running, the login page open and when give the username as "admin@refocus.admin" what is the password need to be used - provided Postgres possword given while installing the Postgres, dint work.

Tried to create new user, just page refreshes and data is not added into the DB.

Getting error 404

Let me know, what is missing?

**Comment by harshkothari410** [comment]
I dont understand the issue. Did you not able to connect to postgres or did you not able to signup / login ? @preethi-shekar

**Comment by preethi-shekar** [comment]
Unable to sigup or login.

**Comment by jgraff2** [comment]
@preethi-shekar follow steps 1 and 2 in https://github.com/salesforce/refocus/blob/master/README.md#securing-refocus. Since you already set it up with a non-production environment, the password should already be initialized to "devPassword".

Looks like the quickstart doc needs to be updated to make this clear. Thanks for bringing this up, I will make sure it gets updated.

**Comment by preethi-shekar** [comment]
I used - UserName: admin@refocus.admin   and Password : devPassword, page
refreshed and not able to see home screen.

where is the log file available? that I can check full log information.

[image: image.png]

**Comment by jgraff2** [comment]
@preethi-shekar that means you are now logged in. The default page will be blank until you have installed a lens and created a perspective, as described in the quickstart guide. You should now be able to go /tokens/new to create an API token, which you can then use to set everything up.

**Comment by preethi-shekar** [comment]
Nope, I see log in page, its just gets refreshed and I still see log in
screen, however developer screen shows 200 response code.

can you tell where is the logging enable so that I see the trace and find
the issue.

**Comment by jgraff2** [comment]
The logs should be going to stdout.

**Comment by preethi-shekar** [comment]
did anyone has same issue?, i setup 3 different vmware and have same issue,
unable to log in /signup, do I need to check any configuration?

**Comment by froismo** [comment]
I'm seeing this also, I used docker-compose for bringing it up.  Here is what I see in the console when I browse to a specific perspective.
```
refocus-app_1  | ------------
refocus-app_1  | errorHandler
refocus-app_1  | ------------
refocus-app_1  | GET /v1/lenses/undefined {}
refocus-app_1  | { errors: 
refocus-app_1  |    [ { message: 'An unexpected ResourceNotFoundError occurred.',
refocus-app_1  |        source: 'Lens',
refocus-app_1  |        value: 'undefined',
refocus-app_1  |        type: 'ResourceNotFoundError',
refocus-app_1  |        description: '' } ] }
refocus-app_1  | Status 404: An unexpected ResourceNotFoundError occurred.
refocus-app_1  |     at model.findOne.then (/opt/refocus/api/v1/helpers/verbs/utils.js:441:21)
refocus-app_1  | 
```

**Comment by froismo** [comment]
I've tested with https://github.com/salesforce/refocus/pull/1131 and it was working with that change.

**Comment by jgraff2** [comment]
@froismo sorry about that, the fix is now in master.
That bug was introduced recently; it's not related to the original issue.

**Comment by jgraff2** [comment]
@preethi-shekar were you able to get it working? Did you find anything in the logs?

**Comment by preethi-shekar** [comment]
Nope, I was not able to identify where is the log, I'm NOT using dockers,
dockers is for MAC, can i use the same docker process for Centos ?
