### ISSUE TITLE
Relax validation rules on related link display text

### ISSUE THREAD

**Issue by davidarcher** [salesforce/refocus#1215]
As a user of Refocus, I want to be able to configure related links for aspects to show relevant information at a glance. Sometimes the information I want to display is an email address or a team/group name that contains parenthesis.

The current validation regex for aspects relatedLinks.name field prevents common use cases like showing an email address on a mailto link.

Can we allow common symbols like parenthesis and at-signs in the aspects relatedLinks name field? I would expect just about anything you could type on a normal keyboard would be allowed.

**Comment by cassiodias** [comment]
if you still sying that as valid feature, please create an internal work item. thanks
