### ISSUE TITLE
error when uploading lens

### ISSUE THREAD

**Issue by jaisingh** [salesforce/refocus#281]
Getting the following error when following directions on uploading a lens:

https://salesforce.github.io/refocus/docs/01-quickstart.html , Step 4

```{
  "errors": [
    {
      "message": "request entity too large",
      "source": "",
      "value": "",
      "type": "Error",
      "description": ""
    }
  ]
}```

**Comment by iamigo** [comment]
Hi Jai! How big is the lens library you're trying to upload?

The default payload limit is defined in config.js
`defaultPayloadLimit = '200MB';`
but you can override it with `payloadLimit` environment variable.

**Comment by jaisingh** [comment]
its the MultiTable.zip listed as part of the directions.

**Comment by iamigo** [comment]
Hmmm. The current version there is only 226 KB. Are you testing this in a local dev env on Heroku or some other environment?

**Comment by jaisingh** [comment]
Heroku. I'll send you the URL oob

**Comment by iamigo** [comment]
If you're using Postman, make sure there are no request headers (other than "Authorization", if you have token enforcement enabled).
