### ISSUE TITLE
QuickStart should point to the correct directory for downloading multitable.zip

### ISSUE THREAD

**Issue by jbf-zuora** [salesforce/refocus#282]
[This pag](https://salesforce.github.io/refocus/docs/01-quickstart.html#step-4-install-a-lens)e says "To get the MultiTable lens, git clone this repository. The lens zip archive is under the dist folder."

Iftshould probably say "Download the MultiTable Lens from [here](https://github.com/salesforce/refocus-lens-multitable/tree/master/dist).

**Comment by iamigo** [comment]
https://github.com/salesforce/refocus/pull/283
