### ISSUE TITLE
GUI For adding subjects has several issues (maybe all the same root cause)

### ISSUE THREAD

**Issue by jbf-zuora** [salesforce/refocus#287]
On the /subjects URL GUI:
1. When editing a child subject to add "is published", the parent is lost
2. Entering a parent that does not exist, does not give any error messages.
3. Entering a parent that DOES exist is not haved

Upon further investigation:
When adding a child subject via the GUI, there is no choice to publish it. 
After saving the child appears correctly in the hierarchy.
When you got back in to edit the child to publish it, the parent information disappears, the pulldown becomes a plain text field, and any data there is ignored.

Will share video out of band

**Comment by iamigo** [comment]
Will address in complete UX overhaul.
