### ISSUE TITLE
Images for SSO/OKTA/refocus Configuration

### ISSUE THREAD

**Issue by ghost** [salesforce/refocus#62]
![oktacreatenewapp](https://cloud.githubusercontent.com/assets/20688432/19559807/75e9e844-9686-11e6-8a49-669f634f1451.png)
![oktapicksaml2 0](https://cloud.githubusercontent.com/assets/20688432/19559829/890bd1d0-9686-11e6-9223-875409c2ab37.png)
![oktaurls](https://cloud.githubusercontent.com/assets/20688432/19560091/e74370ea-9687-11e6-989f-ba9fedee910a.png)
![oktaviewsetupinstructions](https://cloud.githubusercontent.com/assets/20688432/19560117/018335ee-9688-11e6-920e-c5d97134397f.png)
![oktasamlsettings](https://cloud.githubusercontent.com/assets/20688432/19560168/27f79422-9688-11e6-9b97-b07dd1990828.png)
![screen shot 2016-10-20 at 5 38 41 am](https://cloud.githubusercontent.com/assets/20688432/19560173/33619f88-9688-11e6-8667-1bc152185759.png)
![refocuspostvalues](https://cloud.githubusercontent.com/assets/20688432/19563513/18318b9e-9695-11e6-934b-b2e86489f6b1.png)

**Comment by iamigo** [comment]
Charlie added the images... ok to close this issue, @jbf-zuora?
