### ISSUE TITLE
add middleware to reject POST/PATCH/PUT requests with invalid attributes in the body

### ISSUE THREAD

**Issue by iamigo** [salesforce/refocus#799]
As a Refocus user, I want a rock-solid API experience--if my requests are invalid, I want them to be rejected, and I want the rejection to include helpful error messages.

Swagger lets these kinds of requests through, and in our controllers we just ignore them.

Create middleware to check the list of fields defined in swagger and reject as 400 BAD REQUEST if the POST/PATCH/PUT request body contains any fields which are not supported.

Acceptance Criteria:
[ ] middleware added to all POST/PATCH/PUT requests
[ ] requests with "extra" or unsupported attributes (i.e. anything beyond the enumeration of fields defined in swagger for each endpoint) are rejected
[ ] error messages include names of fields which are invalid

**Comment by bishwenduk029** [comment]
Hi @iamigo, can I work on this requirement and of course with guidance from you

**Comment by iamigo** [comment]
Hi Bishwendu. That would be great! Please let me know how I can help get you started.

**Comment by bishwenduk029** [comment]
Hi Ian I was planning on starting with following steps:
1.) First build an independent reusable module to check for REST request schema against Swagger defined schema and perform error handling accordingly.
2.) Plug this module into current Refocus application, I am analyzing the codebase for the best place to do the same. But would be needing your help here to do the same.

If you would want to suggest any other approach please do so, I am open to suggestions and implement this tailored to the product's needs.

**Comment by iamigo** [comment]
Yes--that's the exact approach I'd take! There is nothing "Refocus"-y about the problem we're trying to solve here, so a generic middleware is the best approach.

**Comment by bishwenduk029** [comment]
Sure thanks @iamigo , I am continuing with the development as soon as I have some concrete implementation I will share it with you. By the way the code is very nicely documented, I am having absolutely no problem navigating through the source code. It is also a learning for me from code maintenance and architecture perspective.

**Comment by bishwenduk029** [comment]
Hi @iamigo , actually I found the use of **swagger-tools** for validating the requests in the existing codebase and it should send a 400 BAD REQ with proper error message. So i tried to test it, but my local instance of refocus is unable to connect to my docker postgres instance. Can you please help me out here ? Like am I missing some configs or command runs?
I referred:
https://opensource.salesforce.com/refocus/docs/04-quickstartlocal.html

docker ps:
b4351ce89504        postgres            "docker-entrypoint.s…"   11 minutes ago      Up 11 minutes       5432/tcp            postgress

npm run cleanup
npm run start

**Comment by iamigo** [comment]
The validation provided by swagger tools ensures that the params provided in the request body match the data types etc. if those params are specified in the swagger definition for the route, BUT they don't reject requests where the request body has "extra" attributes which are not defined for the route. *That* is what we're trying to achieve here.

**Comment by iamigo** [comment]
I assume you ran "docker-compose up"?
(To be honest I have never used the docker image - I always use a postgres db I have installed on my laptop.)
